version: "3.8"

services:

  mongodb:
    image: mongo:5.0.2-focal
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  redis_partners:
    image: redis:6.2.5-alpine
    container_name: redis-partners
    ports:
      - 6379:6379

  api_partners:
    image: partners_api:dev
    container_name: api-partners
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis_partners

  queue_partners:
    image: partners_api:dev
    container_name: queue-partners
    command: 'python -u consumer.py'
    env_file:
      - .env
    depends_on:
      - api_partners

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - queue_partners
    ports:
      - 8081:8081

volumes:
  mongodb-data:
    name: mongodb-data
  
networks:
    default:
        external:
            name: partners-network
